site_name: Gopkg Documentation
pages:
- Home: index.md
- Getting Started: getting-started.md
- The gopkg.yaml File: gopkg.yaml.md
- Versions and Ranges: versions.md
- Lock file: gopkg.lock.md
- Commands: commands.md
- Resolving Imports: resolving-imports.md
- Vendor Directories: vendor.md
- Plugins: plugins.md
- F.A.Q.: faq.md
theme: readthedocs
