#!/bin/bash

# You can execute me through Gopkg by doing the following:
# - Copy me to a directory on $PATH. _vendor/bin/ will work just fine.
# - Execute `gopkg plugin-example`
# - ???
# - Profit

echo "I received arguments '$@'"

# This should match the directory from which you executed gopkg.
echo "My current working directory is $(pwd)"

# This is the GOPATH for the current gopkg session.
echo "My GOPATH is $GOPATH"

# This is the base directory of your project.
echo "The project directory is $GOPKG_PROJECT"

# This is the location of the gopkg.yaml file.
echo "The Gopkg YAML is in $GOPKG_YAML"

# This is the PATH that the plugin inherited.
echo "My PATH is $PATH"

